// Generated by gencpp from file path_plan/angle.msg
// DO NOT EDIT!


#ifndef PATH_PLAN_MESSAGE_ANGLE_H
#define PATH_PLAN_MESSAGE_ANGLE_H

#include <ros/service_traits.h>


#include <path_plan/angleRequest.h>
#include <path_plan/angleResponse.h>


namespace path_plan
{

struct angle
{

typedef angleRequest Request;
typedef angleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct angle
} // namespace path_plan


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_plan::angle > {
  static const char* value()
  {
    return "f722b4fcc5489fb64570f8162eaa2eed";
  }

  static const char* value(const ::path_plan::angle&) { return value(); }
};

template<>
struct DataType< ::path_plan::angle > {
  static const char* value()
  {
    return "path_plan/angle";
  }

  static const char* value(const ::path_plan::angle&) { return value(); }
};


// service_traits::MD5Sum< ::path_plan::angleRequest> should match 
// service_traits::MD5Sum< ::path_plan::angle > 
template<>
struct MD5Sum< ::path_plan::angleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_plan::angle >::value();
  }
  static const char* value(const ::path_plan::angleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_plan::angleRequest> should match 
// service_traits::DataType< ::path_plan::angle > 
template<>
struct DataType< ::path_plan::angleRequest>
{
  static const char* value()
  {
    return DataType< ::path_plan::angle >::value();
  }
  static const char* value(const ::path_plan::angleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_plan::angleResponse> should match 
// service_traits::MD5Sum< ::path_plan::angle > 
template<>
struct MD5Sum< ::path_plan::angleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_plan::angle >::value();
  }
  static const char* value(const ::path_plan::angleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_plan::angleResponse> should match 
// service_traits::DataType< ::path_plan::angle > 
template<>
struct DataType< ::path_plan::angleResponse>
{
  static const char* value()
  {
    return DataType< ::path_plan::angle >::value();
  }
  static const char* value(const ::path_plan::angleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLAN_MESSAGE_ANGLE_H
