// Generated by gencpp from file path_plan/markerRequest.msg
// DO NOT EDIT!


#ifndef PATH_PLAN_MESSAGE_MARKERREQUEST_H
#define PATH_PLAN_MESSAGE_MARKERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_plan
{
template <class ContainerAllocator>
struct markerRequest_
{
  typedef markerRequest_<ContainerAllocator> Type;

  markerRequest_()
    : marker(0)  {
    }
  markerRequest_(const ContainerAllocator& _alloc)
    : marker(0)  {
  (void)_alloc;
    }



   typedef int16_t _marker_type;
  _marker_type marker;




  typedef boost::shared_ptr< ::path_plan::markerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_plan::markerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct markerRequest_

typedef ::path_plan::markerRequest_<std::allocator<void> > markerRequest;

typedef boost::shared_ptr< ::path_plan::markerRequest > markerRequestPtr;
typedef boost::shared_ptr< ::path_plan::markerRequest const> markerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_plan::markerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_plan::markerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_plan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'path_plan': ['/home/pi/mitra/src/path_plan/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_plan::markerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_plan::markerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_plan::markerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_plan::markerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_plan::markerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_plan::markerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_plan::markerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ae0ec7c15e146a683df6b374730cbd5";
  }

  static const char* value(const ::path_plan::markerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ae0ec7c15e146a6ULL;
  static const uint64_t static_value2 = 0x83df6b374730cbd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_plan::markerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_plan/markerRequest";
  }

  static const char* value(const ::path_plan::markerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_plan::markerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 marker\n\
";
  }

  static const char* value(const ::path_plan::markerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_plan::markerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.marker);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct markerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_plan::markerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_plan::markerRequest_<ContainerAllocator>& v)
  {
    s << indent << "marker: ";
    Printer<int16_t>::stream(s, indent + "  ", v.marker);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLAN_MESSAGE_MARKERREQUEST_H
